import "./globals.css";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "react-tooltip/dist/react-tooltip.css";
import "react-loading-skeleton/dist/skeleton.css";
import "react-photo-view/dist/react-photo-view.css";
import QueryProviders from "@/components/providers/QueryProviders";
import Providers from "@/components/providers/Providers";
import { getServerSettingData } from "@/components/lib/getServerSettingData";
import { merriweather } from "@/utils/font";

export async function generateMetadata() {
  const settingData = await getServerSettingData();
  const logoUrl = settingData?.data[0]?.logo || "VESTORA";

  return {
    title: "VESTORA",
    description: "Generated by VESTORA",
    openGraph: {
      title: "VESTORA",
      description: "Generated by VESTORA",
      images: [
        {
          url: logoUrl,
          alt: "VESTORA Preview Image",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "VESTORA",
      description: "Generated by VESTORA",
      images: [logoUrl],
    },
  };
}

export default async function RootLayout({ children }) {
  const settingData = await getServerSettingData();
  const faviconUrl = settingData?.data[0]?.favicon || "/default-favicon.ico";

  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href={faviconUrl} // Use dynamic favicon or default
          type="image/x-icon"
        />
      </head>
      <body
        className={merriweather.className}
        // style={{ "touch-action": "none" }}
      >
        <Providers>
          <QueryProviders>
            <main>
              {children}
              <ToastContainer
                position="bottom-right"
                autoClose={1500}
                transition={Slide}
                closeOnClick
              />
            </main>
          </QueryProviders>
        </Providers>
      </body>
    </html>
  );
}
