import Contain from "@/components/common/Contain";
import MainCompare from "@/components/compare/MainCompare";

export const metadata = {
  title: "Compare",
  description: "Generated by Classic-eCommerce",
};

const ComparePage = () => {
  return (
    <Contain>
      <MainCompare />
    </Contain>
  );
};

export default ComparePage;
